name: CICD for serverless Application
run-name: ${{ github.acton }} is doing CICD for serverless application

on:
    push:
        branches: [ manin, "*" ]

jobs:
    pre-deply:
        runs-on: ubuntu-latest
        steps:
            - run: echo " ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event"
            - run: echo " ğŸ§ The job is now running on a ${{ github.os }} server hosted by Github"
            - run: echo " ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

    install-dependencies:
        runs-on: ubuntu-latest
        needs: pre-deploy
        steps:
            - name: Check out repository code
            uses: actions/checkout@v3
            - name: Run Installation of Dependencies Commands
            run: npm install